'use client';

import { FormEvent, useMemo, useState } from 'react';

type Promotion = { id: number; code: string; type: 'Phần trăm' | 'Số tiền'; value: number; minimum: number; expires: string; used: number; limit: number; status: 'Đang chạy' | 'Tạm dừng' };
const starter: Promotion[] = [{ id: 1, code: 'GREEN10', type: 'Phần trăm', value: 10, minimum: 300000, expires: '30/09/2026', used: 24, limit: 100, status: 'Đang chạy' }, { id: 2, code: 'WELCOME50', type: 'Số tiền', value: 50000, minimum: 500000, expires: '31/12/2026', used: 8, limit: 50, status: 'Đang chạy' }];
const empty = { code: '', type: 'Phần trăm' as Promotion['type'], value: 10, minimum: 0, expires: '', used: 0, limit: 100, status: 'Đang chạy' as Promotion['status'] };
const money = (value: number) => `${new Intl.NumberFormat('vi-VN').format(value)}đ`;

export default function AdminPromotionsPage() {
  const [promotions, setPromotions] = useState<Promotion[]>(() => { if (typeof window === 'undefined') return starter; const saved = window.localStorage.getItem('plant_shop_promotions_codes'); return saved ? JSON.parse(saved) as Promotion[] : starter; });
  const [draft, setDraft] = useState(empty);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [query, setQuery] = useState('');
  const [notice, setNotice] = useState('');
  const filtered = useMemo(() => promotions.filter((promotion) => promotion.code.toLowerCase().includes(query.toLowerCase())), [promotions, query]);

  function persist(next: Promotion[]) { setPromotions(next); window.localStorage.setItem('plant_shop_promotions_codes', JSON.stringify(next)); const log = JSON.parse(window.localStorage.getItem('plant_shop_change_log') || '[]') as Array<{ time: string; section: string; action: string }>; log.unshift({ time: new Date().toISOString(), section: 'Khuyến mãi', action: 'Cập nhật mã khuyến mãi' }); window.localStorage.setItem('plant_shop_change_log', JSON.stringify(log.slice(0, 100))); }
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!draft.code.trim() || !draft.expires) return; const next = editingId === null ? [...promotions, { ...draft, id: Date.now(), code: draft.code.toUpperCase() }] : promotions.map((promotion) => promotion.id === editingId ? { ...draft, id: editingId, code: draft.code.toUpperCase() } : promotion); persist(next); setDraft(empty); setEditingId(null); setNotice('Đã lưu khuyến mãi.'); window.setTimeout(() => setNotice(''), 2200); }
  function edit(promotion: Promotion) { setEditingId(promotion.id); setDraft({ code: promotion.code, type: promotion.type, value: promotion.value, minimum: promotion.minimum, expires: promotion.expires, used: promotion.used, limit: promotion.limit, status: promotion.status }); }
  function toggle(id: number) { persist(promotions.map((promotion) => promotion.id === id ? { ...promotion, status: promotion.status === 'Đang chạy' ? 'Tạm dừng' : 'Đang chạy' } : promotion)); }
  function remove(id: number) { if (window.confirm('Xóa mã khuyến mãi này?')) persist(promotions.filter((promotion) => promotion.id !== id)); }

  return <div className="admin-crud-page"><div className="admin-page-title"><div><span className="eyebrow">Bán hàng · Khuyến mãi</span><h2>Quản lý khuyến mãi</h2><p>Tạo mã giảm giá, giới hạn lượt dùng và kiểm soát thời hạn chiến dịch.</p></div><span className="admin-record-count">{promotions.length} mã</span></div><div className="admin-crud-layout"><form className="admin-crud-form" onSubmit={submit}><span className="filter-label">Chiến dịch mới</span><h3>{editingId === null ? 'Tạo mã giảm giá' : 'Cập nhật mã'}</h3><label>Mã khuyến mãi<input value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value.toUpperCase() })} placeholder="GREEN10" required /></label><div className="admin-form-row"><label>Loại giảm<select value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as Promotion['type'] })}><option>Phần trăm</option><option>Số tiền</option></select></label><label>Giá trị<input type="number" min="0" value={draft.value} onChange={(event) => setDraft({ ...draft, value: Number(event.target.value) })} /></label></div><div className="admin-form-row"><label>Đơn tối thiểu<input type="number" min="0" value={draft.minimum} onChange={(event) => setDraft({ ...draft, minimum: Number(event.target.value) })} /></label><label>Giới hạn lượt dùng<input type="number" min="1" value={draft.limit} onChange={(event) => setDraft({ ...draft, limit: Number(event.target.value) })} /></label></div><label>Hết hạn<input value={draft.expires} onChange={(event) => setDraft({ ...draft, expires: event.target.value })} placeholder="30/09/2026" required /></label><div className="admin-form-actions"><button className="button button-primary" type="submit">{editingId === null ? 'Tạo khuyến mãi' : 'Lưu thay đổi'}</button>{editingId !== null && <button className="button button-outline" type="button" onClick={() => { setEditingId(null); setDraft(empty); }}>Hủy</button>}</div></form><section className="admin-crud-list"><div className="admin-list-toolbar"><label className="admin-inline-search">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm mã..." /></label><span>{filtered.length} kết quả</span></div>{filtered.map((promotion) => <article className="admin-promotion-row" key={promotion.id}><div><h3>{promotion.code}</h3><small>Đơn từ {money(promotion.minimum)} · Hết hạn {promotion.expires}</small></div><strong>{promotion.type === 'Phần trăm' ? `${promotion.value}%` : money(promotion.value)}</strong><span>{promotion.used}/{promotion.limit} lượt dùng</span><button className={`admin-status ${promotion.status === 'Đang chạy' ? 'is-visible' : ''}`} type="button" onClick={() => toggle(promotion.id)}>{promotion.status}</button><div className="admin-row-actions"><button type="button" onClick={() => edit(promotion)}>Sửa</button><button type="button" onClick={() => remove(promotion.id)}>Xóa</button></div></article>)}</section></div>{notice && <div className="admin-save-notice">✦ {notice}</div>}</div>;
}
