'use client';

import { FormEvent, useEffect, useState } from 'react';

const defaultChannels = { zalo: '0909123456', whatsapp: '84909123456', email: 'hello@plantshop.vn', hotline: '0909123456', enabled: { zalo: true, whatsapp: true, email: true, hotline: true } };

export default function ContactPage() {
  const [channels, setChannels] = useState(defaultChannels);
  const [sourceUrl, setSourceUrl] = useState('');
  const [product, setProduct] = useState('');
  const [form, setForm] = useState({ name: '', contact: '', need: '', related: '' });
  const [notice, setNotice] = useState('');
  useEffect(() => { const saved = window.localStorage.getItem('plant_shop_contact_settings'); if (saved) setChannels({ ...defaultChannels, ...JSON.parse(saved) }); const params = new URLSearchParams(window.location.search); setSourceUrl(params.get('url') || window.location.href); setProduct(params.get('product') || ''); }, []);
  function update(field: keyof typeof form, value: string) { setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001'}/consultations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, contact: form.contact, need: form.need, related: form.related || product, sourceUrl }) }); if (!response.ok) throw new Error('Không thể gửi yêu cầu lúc này.'); setNotice('Đã nhận yêu cầu. Plant Shop sẽ liên hệ lại sớm.'); setForm({ name: '', contact: '', need: '', related: '' }); } catch { setNotice('Không thể kết nối máy chủ. Vui lòng gọi hotline hoặc dùng Zalo.'); } }
  const emailSubject = encodeURIComponent(`Tư vấn Plant Shop${product ? ` · ${product}` : ''}`);
  return <section className="contact-page container"><div className="contact-hero"><span className="eyebrow">Plant Shop · Kết nối</span><h1>Cùng tạo một<br /><em>góc xanh.</em></h1><p>Gửi chúng mình vài dòng về không gian, sản phẩm hoặc dịch vụ bạn đang quan tâm.</p><div className="contact-channel-grid">{channels.enabled.zalo && <a href={`https://zalo.me/${channels.zalo}`} target="_blank" rel="noreferrer"><strong>Zalo</strong><small>{channels.zalo}</small></a>}{channels.enabled.whatsapp && <a href={`https://wa.me/${channels.whatsapp}`} target="_blank" rel="noreferrer"><strong>WhatsApp</strong><small>Nhắn trực tiếp</small></a>}{channels.enabled.email && <a href={`mailto:${channels.email}?subject=${emailSubject}`}><strong>Email</strong><small>{channels.email}</small></a>}{channels.enabled.hotline && <a href={`tel:${channels.hotline}`}><strong>Hotline</strong><small>{channels.hotline}</small></a>}</div></div><form className="consultation-form" onSubmit={submit}><span className="filter-label">Gửi yêu cầu tư vấn</span><h2>Để lại thông tin</h2><label>Họ và tên<input value={form.name} onChange={(event) => update('name', event.target.value)} required placeholder="Nguyễn Minh Anh" /></label><label>Số điện thoại hoặc email<input value={form.contact} onChange={(event) => update('contact', event.target.value)} required placeholder="Bạn muốn nhận phản hồi ở đâu?" /></label><label>Sản phẩm hoặc dịch vụ liên quan<input value={form.related} onChange={(event) => update('related', event.target.value)} placeholder={product || 'Ví dụ: thiết kế văn phòng'} /></label><label>Nhu cầu của bạn<textarea value={form.need} onChange={(event) => update('need', event.target.value)} required rows={5} placeholder="Mô tả không gian, ngân sách hoặc điều bạn đang cần..." /></label><button className="button button-primary" type="submit">Gửi yêu cầu tư vấn →</button>{notice && <p className="form-success" role="status">{notice}</p>}<small>Thông tin được dùng để liên hệ tư vấn, không tự động gửi tin thay bạn.</small></form></section>;
}
