export const adminMenu = [
  { label: 'Tổng quan', href: '/admin' },
  { label: 'Sản phẩm', href: '/admin/san-pham' },
  { label: 'Danh mục', href: '/admin/danh-muc' },
  { label: 'Kho hàng', href: '/admin/kho-hang' },
  { label: 'Đơn hàng', href: '/admin/don-hang' },
  { label: 'Khuyến mãi', href: '/admin/khuyen-mai' },
  { label: 'Tư vấn', href: '/admin/tu-van' },
  { label: 'Dịch vụ', href: '/admin/dich-vu' },
  { label: 'Dự án', href: '/admin/du-an' },
  { label: 'Bài viết', href: '/admin/bai-viet' },
  { label: 'Trang nội dung', href: '/admin/trang-noi-dung' },
  { label: 'Media', href: '/admin/media' },
  { label: 'Đối tác', href: '/admin/doi-tac' },
  { label: 'Giao diện', href: '/admin/giao-dien' },
  { label: 'SEO', href: '/admin/seo' },
  { label: 'Cấu hình', href: '/admin/cau-hinh' },
  { label: 'Người dùng', href: '/admin/nguoi-dung' },
  { label: 'Báo cáo', href: '/admin/bao-cao' },
];
