export type StoryCategory = 'Chăm cây' | 'Làm vườn' | 'Không gian' | 'Câu chuyện cây';

export type Story = {
  slug: string;
  category: StoryCategory;
  title: string;
  excerpt: string;
  readTime: string;
  image: string;
  tone: string;
  lead: string;
  sections: { heading: string; body: string }[];
};

export const stories: Story[] = [
  { slug: 'chon-cay-theo-anh-sang', category: 'Chăm cây', title: 'Chọn cây đúng với ánh sáng trong nhà', excerpt: 'Đọc ánh sáng trong từng góc nhà để chọn một người bạn xanh khỏe lâu dài.', readTime: '4 phút đọc', image: '/assets/images/cat-indoor.jpg', tone: 'story-green', lead: 'Một chậu cây đẹp không chỉ nằm ở hình dáng. Khi được đặt đúng nơi có lượng sáng phù hợp, cây sẽ khỏe hơn, lá bền màu hơn và bạn cũng chăm cây nhàn hơn.', sections: [{ heading: 'Bước 1: Quan sát ánh sáng', body: 'Hãy đứng ở vị trí bạn muốn đặt cây vào ba thời điểm trong ngày. Nếu nơi đó có ánh sáng tự nhiên dịu, không bị nắng gắt chiếu trực tiếp, đó là vùng sáng tán xạ phù hợp với nhiều cây nội thất.' }, { heading: 'Bước 2: Chọn cây theo góc nhà', body: 'Cây Lưỡi Hổ và Kim Tiền chịu được ánh sáng thấp. Monstera, Trầu Bà và Bàng Singapore thích nơi sáng hơn. Với ban công nhiều nắng, hãy ưu tiên Sen Đá hoặc các loại cây lá dày.' }, { heading: 'Bước 3: Để cây thích nghi', body: 'Đừng chuyển cây từ nơi tối ra nắng gắt ngay lập tức. Hãy tăng dần thời gian tiếp xúc ánh sáng trong một đến hai tuần để lá không bị sốc.' }] },
  { slug: 'lich-tuoi-nuoc-cho-nguoi-moi', category: 'Chăm cây', title: 'Lịch tưới nước cho người mới bắt đầu', excerpt: 'Tưới ít hay nhiều không quan trọng bằng tưới đúng: tránh úng và giữ rễ luôn khỏe.', readTime: '5 phút đọc', image: '/assets/images/prod-pothos.jpg', tone: 'story-terra', lead: 'Phần lớn cây trong nhà không chết vì thiếu nước mà vì bị tưới quá thường xuyên. Một lịch tưới tốt bắt đầu từ việc chạm vào đất.', sections: [{ heading: 'Kiểm tra đất trước khi tưới', body: 'Dùng ngón tay kiểm tra lớp đất sâu khoảng hai đến ba centimet. Nếu đất còn ẩm, hãy chờ thêm. Nếu đất khô và tơi, cây đã sẵn sàng nhận nước.' }, { heading: 'Tưới chậm và đủ sâu', body: 'Tưới đều quanh mặt chậu cho đến khi một ít nước thoát ra ở đáy. Cách này giúp toàn bộ bầu đất được làm ẩm thay vì chỉ ướt một điểm trên bề mặt.' }, { heading: 'Đừng để chậu ngâm trong nước', body: 'Sau khi tưới khoảng mười phút, hãy đổ phần nước đọng trong đĩa lót. Rễ cần cả nước và không khí để hô hấp.' }] },
  { slug: 'goc-ban-lam-viec-xanh', category: 'Không gian', title: 'Một góc bàn làm việc có thêm sức sống', excerpt: 'Tạo không gian tập trung dễ chịu bằng một chậu cây nhỏ, ánh sáng và vài thói quen đơn giản.', readTime: '3 phút đọc', image: '/assets/images/cat-desk.jpg', tone: 'story-olive', lead: 'Một góc xanh nhỏ có thể làm dịu nhịp làm việc mỗi ngày. Bí quyết là chọn cây vừa tầm mắt và không chiếm mất vùng thao tác.', sections: [{ heading: 'Chọn cây có dáng gọn', body: 'Cau Tiểu Trâm, Sen Đá và Trầu Bà thủy sinh là những lựa chọn phù hợp cho bàn làm việc. Chúng có dáng đẹp, dễ quan sát và không cần chậu quá lớn.' }, { heading: 'Đặt cây lệch khỏi màn hình', body: 'Đặt cây ở góc bàn, cách màn hình một khoảng vừa đủ để tạo chiều sâu mà không che tầm nhìn. Một nguồn sáng bên hông sẽ giúp lá lên màu đẹp hơn.' }] },
  { slug: 'khi-nao-nen-thay-chau', category: 'Làm vườn', title: 'Khi nào nên thay chậu cho cây?', excerpt: 'Nhận biết dấu hiệu cây cần thêm không gian, đất mới và một chiếc chậu phù hợp hơn.', readTime: '4 phút đọc', image: '/assets/images/cat-pots.jpg', tone: 'story-clay', lead: 'Thay chậu không chỉ để cây trông đẹp hơn. Đó là lúc bạn kiểm tra bộ rễ, làm mới đất và giúp cây có thêm không gian phát triển.', sections: [{ heading: 'Dấu hiệu cây đã chật chậu', body: 'Rễ mọc vòng quanh đáy, đất khô quá nhanh hoặc cây nghiêng liên tục là những dấu hiệu phổ biến. Bạn cũng có thể thấy rễ trồi lên trên mặt đất.' }, { heading: 'Chọn chậu mới lớn hơn vừa đủ', body: 'Chậu mới nên lớn hơn chậu cũ khoảng hai đến năm centimet. Chậu quá lớn giữ nhiều nước, dễ khiến rễ bị úng.' }, { heading: 'Sau khi thay chậu', body: 'Đặt cây ở nơi sáng dịu trong vài ngày đầu, hạn chế bón phân và tưới vừa đủ để cây có thời gian hồi phục.' }] },
  { slug: 'cau-chuyen-monstera', category: 'Câu chuyện cây', title: 'Monstera: từ khu rừng nhiệt đới đến phòng khách', excerpt: 'Vì sao những chiếc lá xẻ lại trở thành biểu tượng của một không gian sống có cá tính?', readTime: '6 phút đọc', image: '/assets/images/prod-monstera.jpg', tone: 'story-green', lead: 'Monstera mang trong mình hình ảnh của những khu rừng nhiệt đới: phóng khoáng, nhiều lớp và luôn có một chút bất ngờ.', sections: [{ heading: 'Chiếc lá kể câu chuyện gì?', body: 'Những đường xẻ giúp lá trưởng thành phân tán sức nặng và đón ánh sáng tốt hơn. Trong nhà, chúng cũng tạo nên một điểm nhấn thị giác rất tự nhiên.' }, { heading: 'Để Monstera lớn cùng bạn', body: 'Cho cây ánh sáng tán xạ, giá thể thoát nước và một cọc rêu để bám. Khi lá mới mở, hãy kiên nhẫn chờ lá cứng lại trước khi di chuyển cây.' }] }
];

export const storyCategories = ['Tất cả', 'Chăm cây', 'Làm vườn', 'Không gian', 'Câu chuyện cây'] as const;
